print("+------------------------------------------------+")
print("|    |                                           |")
print("|   -|          Bobcat, Champ                    |")
print("|  --|          Tribute Liabilities Associate    |")
print("| ---|          Parasail Capital                 |")
print("| ---------                                      |")
print("|  -------      4 Hunger Plaza                   |")
print("|               STE 1400                         |")
print("|               District 12, Panem 00012         |")
print("|                                                |")
print("| Work: (406)-994-4636  @: champ@parasail.com    |")
print("+------------------------------------------------+")
